name: PAQ8PX v216 build
on:
  pull_request:
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hxim/paq8px
          ref: v216
          path: source
      - run: cmake -S source -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --parallel 2
      - uses: actions/upload-artifact@v4
        with:
          name: paq8px-v216-linux
          path: build/paq8px
